Tweaked scripts to clean exits
changed bin_shared/helper/configure_TMPDIR
changed bin_shared/helper/configure_output
changed bin_shared/helper/configure_pip

diff --git a/bin_shared/helper/configure_TMPDIR b/bin_shared/helper/configure_TMPDIR
--- a/bin_shared/helper/configure_TMPDIR
+++ b/bin_shared/helper/configure_TMPDIR
@@ -2,7 +2,11 @@
 
 echo 'INFO:  Configure temporary directory (TMPDIR)'
 
-[[   -z "$TMPDIR" ]] && echo 'FATAL: Missing value for $TMPDIR' && exit 1
-[[ ! -e "$TMPDIR" ]] && echo "INFO:  Creating $TMPDIR" && mkdir -p "$TMPDIR"
-[[ ! -d "$TMPDIR" ]] && echo "FATAL: Missing directory $TMPDIR" && exit 1
-echo ''
+[[   -z "$TMPDIR" ]] && \
+  echo 'FATAL: Missing value for $TMPDIR' && exit 1
+[[ ! -e "$TMPDIR" ]] && \
+  echo "INFO:  Creating $TMPDIR" && \
+  mkdir -p "$TMPDIR"
+[[ ! -d "$TMPDIR" ]] && \
+  echo "FATAL: Missing directory $TMPDIR" && exit 1
+echo 'No-op to exit cleanly'
