Tweak scripts for debugging, enhance .hgignore

diff --git a/bin_shared/helper/configure_TMPDIR b/bin_shared/helper/configure_TMPDIR
--- a/bin_shared/helper/configure_TMPDIR
+++ b/bin_shared/helper/configure_TMPDIR
@@ -2,8 +2,7 @@
 
 echo 'INFO:  Configure temporary directory (TMPDIR)'
 
-[[   -z "$TMPDIR" ]] && \
-  echo 'FATAL: Missing value for $TMPDIR' && exit 1
-[[ ! -e "$TMPDIR" ]] && mkdir -p "$TMPDIR"
-[[ ! -d "$TMPDIR" ]] && \
-  echo "FATAL: Missing directory $TMPDIR" && exit 1
+[[   -z "$TMPDIR" ]] && echo 'FATAL: Missing value for $TMPDIR' && exit 1
+[[ ! -e "$TMPDIR" ]] && echo "INFO:  Creating $TMPDIR" && mkdir -p "$TMPDIR"
+[[ ! -d "$TMPDIR" ]] && echo "FATAL: Missing directory $TMPDIR" && exit 1
+
