Tweaked scripts one more time for clean exits, added new files to sloccount

diff --git a/bin_shared/helper/configure_output b/bin_shared/helper/configure_output
--- a/bin_shared/helper/configure_output
+++ b/bin_shared/helper/configure_output
@@ -3,10 +3,9 @@
 echo 'INFO:  Configure output directory'
 
 [[   -z "$HomeProject" ]] && \
-  echo 'FATAL: Missing value for $HomeProject' && exit 1
+  echo 'FATAL:  Missing value for $HomeProject' && exit 1
 [[ ! -e "$HomeProject/out" ]] && \
   echo "INFO:  Creating $HomeProject/out" && \
   mkdir "$HomeProject/out"
-[[ ! -d "$HomeProject/out" ]] && \
-  echo "FATAL: Missing directory $HomeProject/out" && exit 1
-echo 'No-op to exit cleanly'
+[[   -d "$HomeProject/out" ]] && \
+  echo "INFO:  Directory $HomeProject/out exists"
diff --git a/bin_shared/helper/configure_virtualenv b/bin_shared/helper/configure_virtualenv
--- a/bin_shared/helper/configure_virtualenv
+++ b/bin_shared/helper/configure_virtualenv
@@ -4,9 +4,9 @@ echo 'INFO:  Configure Python virtualenv'
 
 # Verify Pip integration
 [[   -z "$PIP_REQUIRE_VIRTUALENV" ]] && \
-  echo 'FATAL: Missing value for $PIP_REQUIRE_VIRTUALENV' && exit 1
+  echo 'FATAL:  Missing value for $PIP_REQUIRE_VIRTUALENV' && exit 1
 [[   -z "$PIP_RESPECT_VIRTUALENV" ]] && \
-  echo 'FATAL: Missing value for $PIP_RESPECT_VIRTUALENV' && exit 1
+  echo 'FATAL:  Missing value for $PIP_RESPECT_VIRTUALENV' && exit 1
 
 # If the virtual environment does not already exist, create it
 [[ ! -f "$HomeProject/PVE/bin/activate" ]] && \
@@ -16,5 +16,5 @@ echo 'INFO:  Configure Python virtualenv'
 # Activate the Python virtual environment (PVE)
 source "$HomeProject/PVE/bin/activate"
 [[ -z "$VIRTUAL_ENV" ]] && \
-  echo 'FATAL: Missing value for $VIRTUAL_ENV' && exit 1
+  echo 'FATAL:  Missing value for $VIRTUAL_ENV' && exit 1
 export PYTHONHOME=$VIRTUAL_ENV
